### ISSUE TITLE
Different API configuration 

### ISSUE THREAD

**Issue by Samuell1** [thebuildcraft/RemotePlayerWaypointsForXaero#11]
Hey,

looks like API links aren't correct for this map: https://map.majncraft.cz , they use https://map.majncraft.cz/configuration.php for configuration, Thanks

https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/blob/bc62b504630bd98558443120c1b42aa27adfeee1/common/src/main/java/de/the_build_craft/remote_player_waypoints_for_xaero/connections/DynmapConnection.java#L58

**Comment by thebuildcraft** [comment]
Hi,
Thanks for letting me know. It looks like I should really do it the correct way and use something like https://map.majncraft.cz/standalone/config.js and build the urls from that data.
I don't know when I will be able to fix it, but it will probably be in the next release.

**Comment by Samuell1** [comment]
@thebuildcraft Thanks for reply! 

No problem. Can i somehow point it to correct link or somehow overwrite it? Maybe that will be cool option to have. Thanks

**Comment by thebuildcraft** [comment]
That would indeed be a good option... but it is sadly not implemented yet. I will think about a good way to add it.

**Comment by thebuildcraft** [comment]
Hi, I have completely overhauled the link parsing for Dynmap, because it looks like every server has a different link-structure. I have also made it possible that the player / user can input the correct get-request link directly (for the case, that it still doesn't work on some servers...).
Your map-link, and hopefully many more, will work in the next release version.

**Comment by Samuell1** [comment]
@thebuildcraft Amazing job! Thanks a lot for amazing plugin!
