### ISSUE TITLE
Bluemap connection failure

### ISSUE THREAD

**Issue by RaafatTurki** [thebuildcraft/RemotePlayerWaypointsForXaero#14]
Hi, I've tried both dunmap and now I'm on bluemap.

I keep getting the dreaded warning message
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/16624558/4e7ace62-a73b-453d-bf16-a8f7c92e7a21)

bluemap link: `http://45.43.163.66:25786`

**Comment by thebuildcraft** [comment]
Hello. Please make sure you have the server-ip and bluemap link in the config (and that the server entry is set to bluemap). If it still doesn't work, please send me the config file.
Note: the messages in chat after setting the config only shows up because I have debug mode on.
![config3](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/104298589/c6cd3063-4201-4822-aa0d-53969dabe808)

**Comment by RaafatTurki** [comment]
Thanks!
Tried again with the server domain (not ip:port) and it worked just fine.
