### ISSUE TITLE
"Error: Your Dymnap link is broken!"

### ISSUE THREAD

**Issue by TheMrEngMan** [thebuildcraft/RemotePlayerWaypointsForXaero#19]
Hello, I'm glad someone finally updated the original RemotePlayers after it was seemingly abandoned in an unfinished state!

I happened to do the same thing (but never it published anywhere as I don't have the time to work on updates/support):
https://github.com/TheMrEngMan/remoteplayers

I was looking to test this version of the mod but encountered an issue when trying to setup the Dynmap link.
Since I don't have as server to test with I just searched for public Dynmap instances and came across these two:  `https://map.greenfieldmc.net` and `https://earthmc.net/map/aurora`.
However, when configuring these in the mod settings, I get this in chat:
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/68214507/e4353bba-e1d6-430a-a4d2-7b8fdecfcd9c)
Upon further searching I found `https://dynmap.harlonserver.net`, and that seemed to work fine.

That's the actual issue I found, now for the main reason I'm reaching out to you:
I've got a few features in my version that you may like to add to yours, like playerhead skins on minimap icons, using client-side player locations when in range (for minimap), line-of-sight checking, showing relative overworld/nether locations come to mind.
Feel free to add stuff from my version to yours, all I ask is to be credited (co-authoring of commits would be nice) :)

(Also, a great feature of GitHub is the Insights>Network tab to check out if a project has any updated forks)

**Comment by thebuildcraft** [comment]
Hi, thanks for reaching out to me.
You found the one problem that is frustrating me for the whole time since developing this mod: Dynmap servers can have completely different link structures. Then I added a try catch with an option that tries to get the config to then construct the correct links... But those 2 servers you found manage to break all of my methods of getting the http-get-request links. I guess I will just add another try catch option to deal with those.

Now, about your fork. Before I started developing this mod, I looked at the forks of the original mod by ewpratten (in the forks tab, not the network tab). But yours is not listed there, because it is a fork of a fork. So, thanks for telling me about the network tab.
And thank you for letting me copy some of your features. I will of course give you all the credit to those!

**Comment by shayypy** [comment]
I'm also receiving this for my Pl3xmap config (`https://map.xmcnet.work`), is this a similar problem or should I create a different issue?
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/43248357/5bd3513f-bbc1-4490-8890-a7bc96462545)
The error cropped out in the screenshot is a different mod, please disregard

**Comment by thebuildcraft** [comment]
Hi. Thanks for reporting this issue. I have never seen this happening on Pl3xmap before. I can't look at it now, but it should be unrelated. Please open a new issue and send me your config file.
I will have a look at it later.

**Comment by thebuildcraft** [comment]
I have marked this as "completed" because I fixed the issue you found with Dynmap links. I will implement the features from your fork later. And thanks again for letting me know / letting me use them.
