### ISSUE TITLE
Pl3xmap: "/map hide" causes all player waypoints/markers to disappear

### ISSUE THREAD

**Issue by NoNameLmao** [thebuildcraft/RemotePlayerWaypointsForXaero#22]
hey there, really liked the mod, im on my friend's smp which has pl3xmap, but whenever i do `/map hide` all other players visible with this mod disappear on the next waypoint update, im not an admin on the smp so i cant exactly provide technical details, but this only happens for as long as im hidden from the map. once i do `/map show`, everyone reappears again.

just wanted to ask, is this intentional coding of the mod for fair play or a bug on either end? thanks in advance

p.s. no errors are shown on my end, its just as if the mod works but no one else's online

**Comment by thebuildcraft** [comment]
It's not a bug. But also not a fair play feature.
If you hide yourself on the online map, my mod can't know in which dimension you are. It can't look at the vanilla dimension, because some servers have multiple custom overworlds, for example.

But if you really want to use my mod while invisible on the Pl3xMap, you can use the following commands:
1. /remote_player_waypoints_for_xaero open_online_map_config
2. /remote_player_waypoints_for_xaero set_current_dimension_overwrite true
3. /remote_player_waypoints_for_xaero set_current_dimension \<insert a valid world-name from the online config JSON>

Unfortunately, you will have to activate the override each time you open the game, and you will have to manually set the correct dimension each time you go to another dimension.

**Comment by NoNameLmao** [comment]
so it means that the world name is not `world` but something else, and it cant know that?

**Comment by thebuildcraft** [comment]
Yes. The usual names are world, world_nether and world_end (or similar) but if the server has custom names or custom dimensions, any code, that doesn't check in which dimension you are on the online map, will fail.

**Comment by NoNameLmao** [comment]
if i know what the world name is (for example from going into the pl3xmap myself and it adds all those extra parameters at the end of the url automatically, including the world name), will there be a more convenient config option to override the world name? or maybe parse the map url to include the map name

**Comment by thebuildcraft** [comment]
The URL, to get the player data, is the same for all dimensions: `map.example.org/tiles/settings.json`. The problem is, that you would see waypoints for players from other dimensions. And the marker waypoint system also needs the correct world name.

**Comment by NoNameLmao** [comment]
oh i get it now, thank you for the explanation
