### ISSUE TITLE
Your Dynmap link is broken!

### ISSUE THREAD

**Issue by rrwatson** [thebuildcraft/RemotePlayerWaypointsForXaero#39]
Hey there,
Not sure what format I should be using for my server IP and my Weblink. Using Dynmap. If you can provide with an example that'd be greatly appreciated. I am putting my server with the port it is hosted on for my server IP and the Server IP and the port allocated for Dynmap. 
Server IP. XXX.XXX.XXX.XXX:XXXXX
Map Link http://XXX.XXX.XXX.XXX:YYYYY
Any help would be greatly appreciated.

**Comment by rrwatson** [comment]
Hey there,
Below is my map link:
http://51.81.167.195:26999/

**Comment by thebuildcraft** [comment]
Ok. It was actually an issue with the link parsing: I have to make sure to replace " " with "%20"...
The problem was that your world / dimension name had an " " inside, which I have never encountered before.
I have now fixed this issue and will release it together with the 1.21.2 update.
Thank you for reporting this bug!

**Comment by rrwatson** [comment]
Hey there,
Thank you for the fast response! What precisely should I have as the link for my use case right now? Thanks!

**Comment by thebuildcraft** [comment]
You can paste this link in for now: http://51.81.167.195:26999/up/world/Bardo%20Vanilla/1
This will bypass any parsing but will also disable marker waypoints (so you will only see player waypoints).
If that doesn't work, I can send you a fixed pre-release .jar here.
